### ISSUE TITLE
Docs: Adding HA sensors for air and floor temperature

### ISSUE THREAD

**Issue by rct** [ha-warmup/warmup#13]
I've added sensors definitions to Home Assistant that allow easy access to both the air and floor temperatures for graphing, alerting, etc.  I think it might be helpful to have something like this in the documentation.  I didn't add it yet, because there are probably better ways of doing this.

Note: by setting `unit_of_measurement`, Home Assistant automatically did a conversion to Fahrenheit when displayed and/or graphed on my system in the US.

```
sensors:
  - platform: template:
    sensors:
      temperature_master_bath_air:
        friendly_name_template: "{{ states.climate.master_bath.attributes['friendly_name'] }} Air Temperature"
        value_template: '{{ states.climate.master_bath.attributes["air_temperature"] }}'
        unit_of_measurement: "°C"
      temperature_master_bath_floor:
        friendly_name_template: "{{ states.climate.master_bath.attributes['friendly_name'] }} Floor Temperature"
        value_template: '{{ states.climate.master_bath.attributes["floor_temperature"] }}'
        unit_of_measurement: "°C"
```
