### ISSUE TITLE
Wiki example for sensors doesn't seem to work

### ISSUE THREAD

**Issue by tboothman** [ha-warmup/warmup#34]
I tried the config at https://github.com/ha-warmup/warmup/wiki/Configuration-ideas#sensors and i just ended up with two readings with no name or value. I tried the below using state_attr instead and that worked
```yaml
sensors:
  temperature_kitchen_air:
    friendly_name_template: "{{ state_attr('climate.kitchen', 'friendly_name') }} Air Temperature"
    value_template: "{{ state_attr('climate.kitchen', 'air_temperature') }}"
    unit_of_measurement: "°C"
  temperature_kitchen_floor:
    friendly_name_template: "{{ state_attr('climate.kitchen', 'friendly_name') }} Floor Temperature"
    value_template: "{{ state_attr('climate.kitchen', 'floor_temperature') }}"
    unit_of_measurement: "°C"
```

There's probably a syntax error on line `- platform: template:` but I put my sensors in a sensors.yaml instead so I don't know what the right format would be.

For completeness I made a sensors.yaml containing:
```yaml
platform: template
sensors:
  temperature_kitchen_air:
    friendly_name_template: "{{ state_attr('climate.kitchen', 'friendly_name') }} Air Temperature"
    value_template: "{{ state_attr('climate.kitchen', 'air_temperature') }}"
    unit_of_measurement: "°C"
  temperature_kitchen_floor:
    friendly_name_template: "{{ state_attr('climate.kitchen', 'friendly_name') }} Floor Temperature"
    value_template: "{{ state_attr('climate.kitchen', 'floor_temperature') }}"
    unit_of_measurement: "°C"
```
and included it from configuration.yaml like so:
```yaml
sensor: !include sensors.yaml
```
