### ISSUE TITLE
Integration 'warmup' not found

### ISSUE THREAD

**Issue by digimadgirl** [ha-warmup/warmup#55]
Logger: homeassistant.config
Source: config.py:924
First occurred: 4:36:22 PM (1 occurrences)
Last logged: 4:36:22 PM

Platform error: climate - Integration 'warmup' not found.

I've installed via HACS but also added the following lines manually to the configuration.yaml and I get the above message in the log.

```
climate:
  - platform: warmup
    username: m******@gmail.com
    password: *******
```

Files are all in /custom_components/warmup/

Have I done something wrong?  How to I force it to recognise the integration? Restarts haven't helped
